### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by fdobad** [Sigggma/avances-practica-intermedia#2]
usando este [commit ](https://github.com/Sigggma/avances-practica-intermedia/commit/a61c7445dbec9a56a2d5fcaf093bf01fb8f5dc54)

al ejecutar en cmd sale:
```
C:\Users\FernandoBadilla\source\fire\pepo-prac\17-01>python main.py
Traceback (most recent call last):
  File "C:\Users\FernandoBadilla\source\fire\pepo-prac\17-01\main.py", line 6, in <module>
    lib = ctypes.CDLL("./holamundo.dll")  # En Windows
  File "C:\Users\FernandoBadilla\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by Sigggma** [comment]
Lo ejecuto en Ubuntu (app de windows store), con lo mismo que sale en readme (antiguamente instrucciones)

Y se ejecuta normalmente

![image](https://github.com/Sigggma/avances-practica-intermedia/assets/127362576/15bdd329-1aca-4145-b989-95451a584020)

**Comment by fdobad** [comment]
pregunté por windows, respondiste por linux.
favor responder por windows.

**Comment by Sigggma** [comment]
Aquí agregué una versión ejecutable en windows [commit](https://github.com/Sigggma/avances-practica-intermedia/commit/0fab6441effbf42d053492ed59c0efaa35fac54d)

Por alguna razón me dio varios problemas en windows, en linux funcionó de inmediato


gcc -o hola_mundo.exe hola_mundo.c
python main.py
